export type KnowledgeDoc = {
    knowledge_id: string;
    business: '经营成长' | '招商入驻' | '资金结算';
    scene?: '入驻与退出' | '保证金管理';
    title: string;
    type: string;
    file_size: string;
    created_at: string;
    status: '生效中'| '已失效';
    preview?: string; // url or base64 or placeholder
};

export const knowledgeList: KnowledgeDoc[] = [
    { knowledge_id: 'k-001', business: '招商入驻', scene: '入驻与退出', title: '入驻流程与退出规范（v1）', type: 'PDF', file_size: '1.2 MB', created_at: '2025-11-20', status: '生效中', preview: '' },
    { knowledge_id: 'k-002', business: '招商入驻', scene: '保证金管理', title: '保证金收取与退还流程', type: 'DOCX', file_size: '850 KB', created_at: '2025-10-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-003', business: '经营成长', title: '商家成长策略概览', type: 'PDF', file_size: '2.3 MB', created_at: '2025-09-01', status: '生效中', preview: '' },
    { knowledge_id: 'k-004', business: '资金结算', title: '资金结算周期与对账', type: 'XLSX', file_size: '430 KB', created_at: '2025-08-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-005', business: '经营成长', title: '商家运营增长案例合集', type: 'PDF', file_size: '5.1 MB', created_at: '2025-07-22', status: '已失效', preview: '' },
    { knowledge_id: 'k-006', business: '经营成长', title: '新商家冷启动指南', type: 'PDF', file_size: '1.8 MB', created_at: '2025-06-15', status: '生效中', preview: '' },
    { knowledge_id: 'k-007', business: '招商入驻', scene: '入驻与退出', title: '特殊类目入驻资质要求', type: 'DOCX', file_size: '967 KB', created_at: '2025-05-28', status: '生效中', preview: '' },
    { knowledge_id: 'k-008', business: '资金结算', title: '跨境结算汇率说明', type: 'XLSX', file_size: '612 KB', created_at: '2025-05-10', status: '生效中', preview: '' },
    { knowledge_id: 'k-009', business: '经营成长', title: '广告投放效果优化手册', type: 'PPTX', file_size: '3.2 MB', created_at: '2025-04-22', status: '已失效', preview: '' },
    { knowledge_id: 'k-010', business: '招商入驻', scene: '保证金管理', title: '保证金补缴与扣除规则', type: 'PDF', file_size: '1.1 MB', created_at: '2025-03-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-011', business: '资金结算', title: '月度结算异常处理流程', type: 'DOCX', file_size: '789 KB', created_at: '2025-03-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-012', business: '经营成长', title: '高价值用户运营策略', type: 'PDF', file_size: '2.7 MB', created_at: '2025-02-20', status: '生效中', preview: '' },
    { knowledge_id: 'k-013', business: '招商入驻', scene: '入驻与退出', title: '品牌旗舰店入驻标准', type: 'DOCX', file_size: '923 KB', created_at: '2025-01-28', status: '生效中', preview: '' },
    { knowledge_id: 'k-014', business: '资金结算', title: '结算账户变更申请指引', type: 'PDF', file_size: '1.4 MB', created_at: '2025-01-15', status: '生效中', preview: '' },
    { knowledge_id: 'k-015', business: '经营成长', title: '商品详情页转化率优化', type: 'PPTX', file_size: '4.5 MB', created_at: '2024-12-30', status: '已失效', preview: '' },
    { knowledge_id: 'k-016', business: '招商入驻', scene: '保证金管理', title: '保证金冻结与解冻说明', type: 'XLSX', file_size: '534 KB', created_at: '2024-12-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-017', business: '资金结算', title: '季度对账差异处理指南', type: 'PDF', file_size: '1.9 MB', created_at: '2024-12-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-018', business: '经营成长', title: '直播带货运营规范', type: 'DOCX', file_size: '1.6 MB', created_at: '2024-11-22', status: '生效中', preview: '' },
    { knowledge_id: 'k-019', business: '招商入驻', scene: '入驻与退出', title: '个体工商户入驻指引', type: 'PDF', file_size: '2.1 MB', created_at: '2024-11-10', status: '生效中', preview: '' },
    { knowledge_id: 'k-020', business: '资金结算', title: '退款订单结算处理', type: 'XLSX', file_size: '678 KB', created_at: '2024-10-28', status: '已失效', preview: '' },
    { knowledge_id: 'k-021', business: '经营成长', title: '会员体系建设指南', type: 'PDF', file_size: '3.3 MB', created_at: '2024-10-15', status: '生效中', preview: '' },
    { knowledge_id: 'k-022', business: '招商入驻', scene: '保证金管理', title: '保证金比例调整通知', type: 'DOCX', file_size: '845 KB', created_at: '2024-09-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-023', business: '资金结算', title: '手续费率说明文档', type: 'PDF', file_size: '1.2 MB', created_at: '2024-09-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-024', business: '经营成长', title: '短视频内容创作手册', type: 'PPTX', file_size: '5.8 MB', created_at: '2024-09-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-025', business: '招商入驻', scene: '入驻与退出', title: '店铺转让与承接流程', type: 'DOCX', file_size: '1.1 MB', created_at: '2024-08-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-026', business: '资金结算', title: '提现到账时间说明', type: 'XLSX', file_size: '456 KB', created_at: '2024-08-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-027', business: '经营成长', title: '私域流量运营攻略', type: 'PDF', file_size: '2.4 MB', created_at: '2024-07-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-028', business: '招商入驻', scene: '保证金管理', title: '保证金发票申请流程', type: 'PDF', file_size: '987 KB', created_at: '2024-07-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-029', business: '资金结算', title: '供应链金融结算指引', type: 'DOCX', file_size: '1.7 MB', created_at: '2024-07-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-030', business: '经营成长', title: '大促活动报名指南', type: 'XLSX', file_size: '2.9 MB', created_at: '2024-06-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-031', business: '招商入驻', scene: '入驻与退出', title: '跨境电商入驻政策', type: 'PDF', file_size: '3.1 MB', created_at: '2024-06-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-032', business: '资金结算', title: '发票管理与结算关联', type: 'DOCX', file_size: '1.3 MB', created_at: '2024-05-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-033', business: '经营成长', title: '客服团队管理手册', type: 'PPTX', file_size: '4.2 MB', created_at: '2024-05-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-034', business: '招商入驻', scene: '保证金管理', title: '保证金预警机制说明', type: 'XLSX', file_size: '567 KB', created_at: '2024-05-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-035', business: '资金结算', title: '分账系统操作手册', type: 'PDF', file_size: '2.0 MB', created_at: '2024-04-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-036', business: '经营成长', title: '爆款打造方法论', type: 'DOCX', file_size: '1.5 MB', created_at: '2024-04-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-037', business: '招商入驻', scene: '入驻与退出', title: '经销商入驻合作协议', type: 'PDF', file_size: '2.8 MB', created_at: '2024-03-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-038', business: '资金结算', title: '结算数据报表模板', type: 'XLSX', file_size: '823 KB', created_at: '2024-03-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-039', business: '经营成长', title: '用户评价管理规范', type: 'PDF', file_size: '1.6 MB', created_at: '2024-03-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-040', business: '招商入驻', scene: '保证金管理', title: '历史保证金迁移方案', type: 'DOCX', file_size: '1.2 MB', created_at: '2024-02-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-041', business: '资金结算', title: '虚拟货币结算政策', type: 'PDF', file_size: '3.4 MB', created_at: '2024-02-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-042', business: '经营成长', title: '新品上市推广策略', type: 'PPTX', file_size: '5.3 MB', created_at: '2024-01-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-043', business: '招商入驻', scene: '入驻与退出', title: '快时尚类目入驻标准', type: 'DOCX', file_size: '945 KB', created_at: '2024-01-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-044', business: '资金结算', title: '延迟结算申诉流程', type: 'XLSX', file_size: '678 KB', created_at: '2024-01-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-045', business: '经营成长', title: '供应链协同管理', type: 'PDF', file_size: '2.2 MB', created_at: '2023-12-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-046', business: '招商入驻', scene: '保证金管理', title: '保证金利息计算规则', type: 'PDF', file_size: '876 KB', created_at: '2023-12-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-047', business: '资金结算', title: '结算周期变更申请表', type: 'DOCX', file_size: '512 KB', created_at: '2023-11-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-048', business: '经营成长', title: '社群营销实战案例', type: 'XLSX', file_size: '3.7 MB', created_at: '2023-11-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-049', business: '招商入驻', scene: '入驻与退出', title: '数码家电类目入驻细则', type: 'PDF', file_size: '4.1 MB', created_at: '2023-11-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-050', business: '资金结算', title: '跨境汇款结算指引', type: 'PPTX', file_size: '2.5 MB', created_at: '2023-10-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-051', business: '经营成长', title: '数据驱动决策手册', type: 'DOCX', file_size: '1.9 MB', created_at: '2023-10-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-052', business: '招商入驻', scene: '保证金管理', title: '保证金最低额度标准', type: 'XLSX', file_size: '445 KB', created_at: '2023-09-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-053', business: '资金结算', title: '结算异常自动预警', type: 'PDF', file_size: '1.8 MB', created_at: '2023-09-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-054', business: '经营成长', title: '会员积分体系设计', type: 'DOCX', file_size: '2.6 MB', created_at: '2023-09-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-055', business: '招商入驻', scene: '入驻与退出', title: '食品生鲜类目准入规则', type: 'PDF', file_size: '3.8 MB', created_at: '2023-08-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-056', business: '资金结算', title: '代收代付结算协议', type: 'XLSX', file_size: '789 KB', created_at: '2023-08-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-057', business: '经营成长', title: '商品定价策略指南', type: 'PPTX', file_size: '4.7 MB', created_at: '2023-07-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-058', business: '招商入驻', scene: '保证金管理', title: '保证金争议处理流程', type: 'DOCX', file_size: '1.4 MB', created_at: '2023-07-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-059', business: '资金结算', title: '供应商结算优先级规则', type: 'PDF', file_size: '2.3 MB', created_at: '2023-07-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-060', business: '经营成长', title: '节假日营销日历', type: 'XLSX', file_size: '1.1 MB', created_at: '2023-06-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-061', business: '招商入驻', scene: '入驻与退出', title: '美妆个护类目入驻指南', type: 'PDF', file_size: '5.5 MB', created_at: '2023-06-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-062', business: '资金结算', title: '结算手续费计算明细', type: 'DOCX', file_size: '632 KB', created_at: '2023-05-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-063', business: '经营成长', title: '竞品分析方法论', type: 'XLSX', file_size: '3.2 MB', created_at: '2023-05-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-064', business: '招商入驻', scene: '保证金管理', title: '保证金催缴通知模板', type: 'PDF', file_size: '789 KB', created_at: '2023-05-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-065', business: '资金结算', title: '预付款结算管理规范', type: 'PPTX', file_size: '2.1 MB', created_at: '2023-04-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-066', business: '经营成长', title: '售后服务标准流程', type: 'DOCX', file_size: '1.7 MB', created_at: '2023-04-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-067', business: '招商入驻', scene: '入驻与退出', title: '家居建材类目入驻要求', type: 'PDF', file_size: '4.4 MB', created_at: '2023-03-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-068', business: '资金结算', title: '结算数据API对接文档', type: 'XLSX', file_size: '956 KB', created_at: '2023-03-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-069', business: '经营成长', title: 'KOL合作策略指南', type: 'PDF', file_size: '3.5 MB', created_at: '2023-03-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-070', business: '招商入驻', scene: '保证金管理', title: '保证金凭证管理规范', type: 'DOCX', file_size: '1.0 MB', created_at: '2023-02-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-071', business: '资金结算', title: '多门店结算管理方案', type: 'XLSX', file_size: '1.8 MB', created_at: '2023-02-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-072', business: '经营成长', title: '用户画像分析模板', type: 'PPTX', file_size: '6.2 MB', created_at: '2023-01-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-073', business: '招商入驻', scene: '入驻与退出', title: '母婴用品类目入驻细则', type: 'DOCX', file_size: '2.9 MB', created_at: '2023-01-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-074', business: '资金结算', title: '结算风控管理规范', type: 'PDF', file_size: '2.4 MB', created_at: '2023-01-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-075', business: '经营成长', title: '库存管理最佳实践', type: 'XLSX', file_size: '1.3 MB', created_at: '2022-12-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-076', business: '招商入驻', scene: '保证金管理', title: '保证金退款时效说明', type: 'PDF', file_size: '654 KB', created_at: '2022-12-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-077', business: '资金结算', title: '平台补贴结算规则', type: 'DOCX', file_size: '1.5 MB', created_at: '2022-11-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-078', business: '经营成长', title: 'A/B测试实施指南', type: 'XLSX', file_size: '4.0 MB', created_at: '2022-11-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-079', business: '招商入驻', scene: '入驻与退出', title: '汽车用品类目入驻流程', type: 'PDF', file_size: '3.9 MB', created_at: '2022-11-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-080', business: '资金结算', title: '结算异常人工介入流程', type: 'PPTX', file_size: '1.9 MB', created_at: '2022-10-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-081', business: '经营成长', title: '数据可视化分析指南', type: 'DOCX', file_size: '2.8 MB', created_at: '2022-10-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-082', business: '招商入驻', scene: '保证金管理', title: '保证金账户合并说明', type: 'XLSX', file_size: '723 KB', created_at: '2022-09-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-083', business: '资金结算', title: '供应链金融准入条件', type: 'PDF', file_size: '2.2 MB', created_at: '2022-09-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-084', business: '经营成长', title: '商家成长评分体系', type: 'DOCX', file_size: '1.8 MB', created_at: '2022-09-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-085', business: '招商入驻', scene: '入驻与退出', title: '图书音像类目入驻规范', type: 'PDF', file_size: '5.0 MB', created_at: '2022-08-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-086', business: '资金结算', title: '结算周期选择指南', type: 'XLSX', file_size: '612 KB', created_at: '2022-08-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-087', business: '经营成长', title: '直播话术库与脚本', type: 'PPTX', file_size: '3.6 MB', created_at: '2022-07-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-088', business: '招商入驻', scene: '保证金管理', title: '保证金转账操作指引', type: 'DOCX', file_size: '934 KB', created_at: '2022-07-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-089', business: '资金结算', title: '结算审计应对指南', type: 'PDF', file_size: '2.7 MB', created_at: '2022-07-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-090', business: '经营成长', title: '私域工具使用手册', type: 'XLSX', file_size: '1.4 MB', created_at: '2022-06-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-091', business: '招商入驻', scene: '入驻与退出', title: '宠物用品类目入驻指南', type: 'PDF', file_size: '4.3 MB', created_at: '2022-06-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-092', business: '资金结算', title: '结算数据备份与恢复', type: 'DOCX', file_size: '823 KB', created_at: '2022-05-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-093', business: '经营成长', title: '用户生命周期管理', type: 'XLSX', file_size: '3.1 MB', created_at: '2022-05-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-094', business: '招商入驻', scene: '保证金管理', title: '保证金流水查询方法', type: 'PDF', file_size: '567 KB', created_at: '2022-05-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-095', business: '资金结算', title: '结算异常案例集', type: 'PPTX', file_size: '2.3 MB', created_at: '2022-04-25', status: '已失效', preview: '' },
    { knowledge_id: 'k-096', business: '经营成长', title: '内容营销创作规范', type: 'DOCX', file_size: '1.9 MB', created_at: '2022-04-12', status: '生效中', preview: '' },
    { knowledge_id: 'k-097', business: '招商入驻', scene: '入驻与退出', title: '运动户外类目入驻要求', type: 'PDF', file_size: '3.3 MB', created_at: '2022-03-30', status: '生效中', preview: '' },
    { knowledge_id: 'k-098', business: '资金结算', title: '结算系统升级通知', type: 'XLSX', file_size: '734 KB', created_at: '2022-03-18', status: '生效中', preview: '' },
    { knowledge_id: 'k-099', business: '经营成长', title: '新兴品类增长机会', type: 'PDF', file_size: '2.6 MB', created_at: '2022-03-05', status: '生效中', preview: '' },
    { knowledge_id: 'k-100', business: '招商入驻', scene: '保证金管理', title: '保证金充值渠道说明', type: 'DOCX', file_size: '891 KB', created_at: '2022-02-25', status: '已失效', preview: '' }
];


